apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-operator.yaml
- grafana-app.yaml
- dashboards
- https://github.com/redhat-appstudio/o11y/config/probes/monitoring/grafana/base?ref=c1b5f5e63ec50c33d64ccc0407ea096c0f8970c8
- https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/grafana/base?ref=c1b5f5e63ec50c33d64ccc0407ea096c0f8970c8
