apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/redhat-appstudio/application-service/config/default?ref=b91ffed33eed2d9d175645d6c1c0c780b619fc69


components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: b91ffed33eed2d9d175645d6c1c0c780b619fc69

configMapGenerator:
  - literals:
      - GITHUB_ORG=""
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace


namespace: application-service