resources:
- allow-argocd-to-manage.yaml
- https://github.com/redhat-appstudio/jvm-build-service/deploy/crds/base?ref=fc28ca0e1997a6e0649b9b24076951f6fb288a54
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/base?ref=fc28ca0e1997a6e0649b9b24076951f6fb288a54
- https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/config?ref=fc28ca0e1997a6e0649b9b24076951f6fb288a54
- monitoring.yaml
- rbac

# Skip applying the jvm-build-service operands (SystemConfig) while the jvm-build-service operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

namespace: jvm-build-service

images:
- name: hacbs-jvm-operator
  newName: quay.io/redhat-appstudio/hacbs-jvm-controller
  newTag: fc28ca0e1997a6e0649b9b24076951f6fb288a54

patches:
- path: ./operator_env_patch.yaml
  target:
    kind: Deployment
    name: hacbs-jvm-operator

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
