apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - ../../../base/external-secrets
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/overlays/openshift_aws?ref=86dd2193af889bb58e5ac991ea289df7e15d9048
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/monitoring/prometheus/base?ref=86dd2193af889bb58e5ac991ea289df7e15d9048
  - spi-aws-credentials-external-secret.yaml

namespace: spi-system

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: 86dd2193af889bb58e5ac991ea289df7e15d9048
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: 86dd2193af889bb58e5ac991ea289df7e15d9048

patches:
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
  - target:
      kind: ConfigMap
      name: shared-environment-config
    path: config-patch.json
  - path: delete-shared-configuration-file.yaml
