apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - https://github.com/redhat-appstudio/remote-secret/config/overlays/openshift_aws?ref=4ab990acc7cde19e686ccfdd72a9a88549bce96f
  - https://github.com/redhat-appstudio/remote-secret/config/monitoring/prometheus?ref=4ab990acc7cde19e686ccfdd72a9a88549bce96f
  - aws-credentials-external-secret.yaml

namespace: remotesecret

images:
  - name:  quay.io/redhat-appstudio/remote-secret-controller
    newName: quay.io/redhat-appstudio/remote-secret-controller
    newTag: 4ab990acc7cde19e686ccfdd72a9a88549bce96f

patches:
  - target:
      kind: Deployment
      name: remote-secret-controller-manager
    path: operator-limits-patch.json
