resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/integration-service/config/default?ref=c94d063831f4be71fe8274bca7cec8cc20f1a743
- integration.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: c94d063831f4be71fe8274bca7cec8cc20f1a743

namespace: integration-service

patches:
  - path: ./manager_resources_patch.yaml
